// Import External Packages
import fs from "fs"
import path from "path"

/**
 * Asynchronously checks if a given path exists and is a directory.
 * @param dirPath - The path to check.
 */
const isDirectory = async (dirPath) => {
  try {
    const stats = await fs.promises.stat(dirPath)
    return stats.isDirectory()
  } catch {
    return false
  }
}

/**
 * Aggregates SQL migration files from a single module into a single file.
 * @param {string} moduleName - The name of the module to aggregate migrations for
 */
const aggregateSingleModuleMigrations = async (moduleName) => {
  try {
    // Define base paths
    const projectRoot = path.resolve(import.meta.dirname, "./../")
    console.log(`🚀 Aggregating migrations for module: ${moduleName}`)
    const appRoot = path.join(projectRoot, "supabase", "db")
    const migrationsOutputDir = path.join(projectRoot, "supabase", "migrations")

    // Ensure the output directory exists
    await fs.promises.mkdir(migrationsOutputDir, { recursive: true })

    // Define the module path
    const modulePath = path.join(appRoot, moduleName)
    
    // Check if module directory exists
    const moduleExists = await isDirectory(modulePath)
    if (!moduleExists) {
      console.error(`❌ Module directory not found: ${modulePath}`)
      process.exit(1)
    }

    // Generate output filename with current date and module name
    const currentDate = new Date()
    const yyyy = currentDate.getFullYear()
    const mm = String(currentDate.getMonth() + 1).padStart(2, "0") // Months start at 0
    const dd = String(currentDate.getDate()).padStart(2, "0")
    const outputFileName = `${yyyy}${mm}${dd}_${moduleName}.sql`
    const outputPath = path.join(migrationsOutputDir, outputFileName)

    // Initialize an array to hold migration contents
    const aggregatedMigrations = []

    // Initialize an array to hold migration file metadata
    const migrationFiles = []

    console.log(`📂 Processing Module: ${moduleName}`)

    // Read all .sql files in the module directory
    const files = await fs.promises.readdir(modulePath)
    const sqlFiles = files.filter((file) => file.endsWith(".sql"))

    if (sqlFiles.length === 0) {
      console.warn(`❌ No migration files found in module: ${moduleName}`)
      return
    }

    for (const sqlFile of sqlFiles) {
      console.log(`   📄 Adding Migration: ${sqlFile}`)
      const filePath = path.join(modulePath, sqlFile)
      let fileContent = await fs.promises.readFile(filePath, "utf-8")
      fileContent = fileContent.replace("BEGIN;", "").replace("COMMIT;", "")

      // Push migration file data for sorting
      migrationFiles.push({
        moduleName,
        fileName: sqlFile,
        filePath,
        content: fileContent.trim()
      })
    }

    // Sort migration files based on filename (assuming prefix numbering)
    migrationFiles.sort((a, b) => {
      const aPrefix = a.fileName.split("_")[0]
      const bPrefix = b.fileName.split("_")[0]
      return aPrefix.localeCompare(bPrefix, undefined, { numeric: true })
    })

    for (const migration of migrationFiles) {
      aggregatedMigrations.push(
        `-- Module: ${migration.moduleName}, File: ${migration.fileName}`
      )
      aggregatedMigrations.push(migration.content)
      aggregatedMigrations.push("\n") // Add a newline for separation
    }

    // Define the disclaimer
    const disclaimer = `
        -- ******************************************************************************
        -- *                AUTOGENERATED FILE                                          *
        -- *  This file is automatically generated by the single module migration      *
        -- *  aggregation script. Do not edit this file directly.                      *
        -- *  To make changes, modify the individual module                             *
        -- *  migration files located in backend/supabase/db/${moduleName}/*.sql      *
        -- ******************************************************************************
        `

    const preamble = `BEGIN;`
    const postamble = `COMMIT;`

    const finalContent = [
      disclaimer,
      preamble,
      ...aggregatedMigrations,
      postamble
    ].join("\n")

    // Write the aggregated migrations to the output file
    await fs.promises.writeFile(outputPath, finalContent, "utf-8")

    console.log(
      `✅ Successfully aggregated ${migrationFiles.length} migration(s) for module '${moduleName}' into ${path.relative(
        projectRoot,
        outputPath
      )}`
    )
  } catch (error) {
    console.error("❌ Error aggregating migrations:", error)
    process.exit(1)
  }
}

// Get module name from command line arguments
const moduleName = process.argv[2]

if (!moduleName) {
  console.error("❌ Please provide a module name as an argument")
  console.log("Usage: node aggregate_migrations_single.mjs <module-name>")
  console.log("Example: node aggregate_migrations_single.mjs payment-system")
  process.exit(1)
}

// Execute the aggregation
aggregateSingleModuleMigrations(moduleName)
