
        -- ******************************************************************************
        -- *                AUTOGENERATED FILE                                          *
        -- *  This file is automatically generated by the migration                     *
        -- *  aggregation script. Do not edit this file directly.                       *
        -- *  To make changes, modify the individual module                             *
        -- *  migration files located in backend/[MODULE]/migrations/*.sql    *
        -- ******************************************************************************
        
BEGIN;
-- Module: user-management, File: 100_20260227_tables.sql
-- ---------------------------
-- MODULE NAME: User Management
-- MODULE DATE: 20260227
-- MODULE SCOPE: Tables
-- ---------------------------



-- ---------------------------
-- Users
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    is_super_admin BOOLEAN DEFAULT FALSE,
    is_email_verified BOOLEAN DEFAULT false,
    email_verification_token TEXT,
    email_verification_token_expires TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


COMMENT ON COLUMN public.users.is_super_admin IS 'Whether the user has super admin privileges (e.g. manage module_configs)';
COMMENT ON COLUMN public.users.is_email_verified IS 'Whether the user has verified their email';
COMMENT ON COLUMN public.users.email_verification_token IS 'Hashed token for email verification link';
COMMENT ON COLUMN public.users.email_verification_token_expires IS 'Expiry for email_verification_token';

-- ---------------------------
-- User Profiles
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.user_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id UUID REFERENCES public.users(id) ON DELETE CASCADE,
    avatar_url TEXT,
    website_url TEXT,
    description TEXT,
    tag_line TEXT,
    location TEXT,
    facebook_url TEXT,
    youtube_url TEXT,
    twitter_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE(owner_id)
);

COMMENT ON TABLE public.user_profiles IS 'Extended user profile information separated from core users table';
COMMENT ON COLUMN public.user_profiles.owner_id IS 'Reference to the user who owns this profile';
COMMENT ON COLUMN public.user_profiles.website_url IS 'User website URL (renamed from website)';

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: feedback, File: 101_20260311_tables.sql
-- ---------------------------
-- MODULE NAME: Feedback
-- MODULE DATE: 20260311
-- MODULE SCOPE: Tables
-- ---------------------------



CREATE TABLE IF NOT EXISTS public.feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    feedback_type TEXT,
    url TEXT,
    description TEXT,
    email TEXT,
    is_handled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE public.feedback IS 'User feedback (propose, report, general). Anonymous submit; list/update by app roles.';


-- Module: user-auth, File: 102_20260227_tables.sql
-- ---------------------------
-- MODULE NAME: User Auth
-- MODULE DATE: 20260227
-- MODULE SCOPE: Tables
-- ---------------------------



-- ---------------------------
-- Refresh Token
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT false,
    revoked_at TIMESTAMPTZ,
    replaced_by TEXT,
    ip_address TEXT,
    user_agent TEXT
);

-- ---------------------------
-- Users (OAuth provider columns; table lives in user-management)
-- ---------------------------

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS provider TEXT,
ADD COLUMN IF NOT EXISTS provider_id TEXT;

COMMENT ON COLUMN public.users.provider IS 'OAuth provider name: google, github, generic';
COMMENT ON COLUMN public.users.provider_id IS 'Provider-specific user id';

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: organization, File: 103_20260309_tables.sql
-- ---------------------------
-- MODULE NAME: Organization
-- MODULE DATE: 20260309
-- MODULE SCOPE: Tables
-- ---------------------------
-- Prefix 103 ensures this runs after user-management (101, creates users) and user-auth (102).
-- user_organizations references public.users(id).



-- ---------------------------
-- Organization role (membership)
-- ---------------------------

DO $$ BEGIN
    CREATE TYPE public.workspace_membership_role AS ENUM ('user', 'admin', 'superadmin');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

COMMENT ON TYPE public.workspace_membership_role IS 'Role of a user within a workspace/organization membership';

-- ---------------------------
-- Organizations
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    api_key TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE public.organizations IS 'Organizations (workspaces/tenants)';
COMMENT ON COLUMN public.organizations.api_key IS 'Optional API key for programmatic access';

-- ---------------------------
-- User-Organization membership
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.user_organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    role public.workspace_membership_role NOT NULL DEFAULT 'user',
    disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT uq_user_organization UNIQUE (user_id, organization_id)
);

COMMENT ON TABLE public.user_organizations IS 'Junction: users belong to organizations with a role';
COMMENT ON COLUMN public.user_organizations.role IS 'workspace_membership_role (user | admin | superadmin)';
COMMENT ON COLUMN public.user_organizations.disabled IS 'When true, membership is inactive';

-- ---------------------------
-- Organization invites (pending)
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.organization_invites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'admin')),
    invited_by_user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

COMMENT ON TABLE public.organization_invites IS 'Pending workspace invites (by email); invitee can accept from list or via link';

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: config, File: 104_20260311_tables.sql
-- ---------------------------
-- MODULE NAME: CONFIG
-- MODULE DATE: 20260311
-- MODULE SCOPE: Tables
-- ---------------------------



-- ---------------------------
-- MODULE CONFIGS
-- ---------------------------

CREATE TABLE public.module_configs (
  module_name TEXT PRIMARY KEY,
  config JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: blog, File: 104_20260313_tables.sql
-- ---------------------------
-- MODULE NAME: Blog System Tables
-- MODULE DATE: 20260313
-- MODULE SCOPE: Tables
-- ---------------------------



-- ---------------------------
-- Blog Topics Table
-- ---------------------------
CREATE TABLE IF NOT EXISTS public.blog_topics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    parent_id UUID REFERENCES public.blog_topics(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- ---------------------------
-- Blog Posts Table
-- ---------------------------
CREATE TABLE IF NOT EXISTS public.blog_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    topic_id UUID REFERENCES public.blog_topics(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    content TEXT NOT NULL,
    hero_image_filename TEXT,
    is_sponsored BOOLEAN NOT NULL DEFAULT false,
    is_admin_approved BOOLEAN NOT NULL DEFAULT false,
    is_user_published BOOLEAN NOT NULL DEFAULT false,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    view_count INTEGER NOT NULL DEFAULT 0,
    like_count INTEGER NOT NULL DEFAULT 0,
    reading_time_minutes INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    published_at TIMESTAMPTZ
);

-- ---------------------------
-- Blog Comments Table
-- ---------------------------
CREATE TABLE IF NOT EXISTS public.blog_comments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id UUID REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    parent_id UUID REFERENCES public.blog_comments(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    is_approved BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

-- ---------------------------
-- Blog Activities Table
-- ---------------------------
CREATE TABLE IF NOT EXISTS public.blog_activities (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    post_id UUID REFERENCES public.blog_posts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    activity_type TEXT NOT NULL CHECK (activity_type IN ('view', 'like', 'share', 'comment')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------
-- End of File
-- ---------------------------


-- Module: rbac, File: 105_20260311_tables.sql
-- ---------------------------
-- MODULE NAME: RBAC (Role-Based Access Control)
-- MODULE DATE: 20260311
-- MODULE SCOPE: Tables
-- ---------------------------
-- Runs after user-management (101). user_roles references public.users(id).



-- ---------------------------
-- App permission and role enums
-- ---------------------------

DO $$ BEGIN
    CREATE TYPE public.app_permission AS ENUM (
        'users.manage_roles'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    CREATE TYPE public.app_role AS ENUM (
        'editor',
        'support',
        'admin'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;


COMMENT ON TYPE public.app_permission IS 'Application-level permissions for fine-grained access control';
COMMENT ON TYPE public.app_role IS 'App roles: editor (blog only), support (feedback only), admin (all + manage roles)';

-- ---------------------------
-- User Roles Table
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    role public.app_role NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    created_by UUID REFERENCES public.users(id),
    UNIQUE (user_id, role)
);

COMMENT ON TABLE public.user_roles IS 'Maps users (public.users.id) to app roles. Distinct from workspace membership (workspace_membership_role).';
COMMENT ON COLUMN public.user_roles.user_id IS 'References public.users(id)';
COMMENT ON COLUMN public.user_roles.role IS 'The app role assigned to the user';
COMMENT ON COLUMN public.user_roles.created_by IS 'User who assigned this role (public.users.id)';

-- ---------------------------
-- Role Permissions Table
-- ---------------------------

CREATE TABLE IF NOT EXISTS public.role_permissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role public.app_role NOT NULL,
    permission public.app_permission NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    UNIQUE (role, permission)
);

COMMENT ON TABLE public.role_permissions IS 'Maps app roles to their permissions';

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: user-management, File: 200_20260227_indexes.sql
-- ---------------------------
-- MODULE NAME: User Management
-- MODULE DATE: 20260227
-- MODULE SCOPE: Indexes
-- ---------------------------



CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users(auth_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_email_verification_token ON public.users(email_verification_token)
    WHERE email_verification_token IS NOT NULL;

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: user-auth, File: 201_20260227_indexes.sql
-- ---------------------------
-- MODULE NAME: User Auth
-- MODULE DATE: 20260227
-- MODULE SCOPE: Indexes
-- ---------------------------

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON public.refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON public.refresh_tokens(token);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON public.refresh_tokens(expires_at);

-- OAuth: unique (provider, provider_id) on public.users
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_provider_provider_id
ON public.users (provider, provider_id)
WHERE provider IS NOT NULL AND provider_id IS NOT NULL;


-- Module: organization, File: 201_20260309_indexes.sql
-- ---------------------------
-- MODULE NAME: Organization
-- MODULE DATE: 20260309
-- MODULE SCOPE: Indexes
-- ---------------------------



CREATE INDEX IF NOT EXISTS idx_organizations_api_key ON public.organizations(api_key)
    WHERE api_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_organizations_user_id ON public.user_organizations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_organizations_organization_id ON public.user_organizations(organization_id);
CREATE INDEX IF NOT EXISTS idx_user_organizations_disabled ON public.user_organizations(disabled);

CREATE INDEX IF NOT EXISTS idx_organization_invites_email ON public.organization_invites(LOWER(email));
CREATE INDEX IF NOT EXISTS idx_organization_invites_organization_id ON public.organization_invites(organization_id);
CREATE INDEX IF NOT EXISTS idx_organization_invites_expires_at ON public.organization_invites(expires_at);

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: rbac, File: 201_20260311_indexes.sql
-- ---------------------------
-- MODULE NAME: RBAC
-- MODULE DATE: 20260311
-- MODULE SCOPE: Indexes
-- ---------------------------

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON public.user_roles(role);

CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON public.role_permissions(role);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission ON public.role_permissions(permission);


-- Module: feedback, File: 201_20260311_indexes.sql
-- ---------------------------
-- MODULE NAME: Feedback
-- MODULE DATE: 20260311
-- MODULE SCOPE: Indexes
-- ---------------------------

CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON public.feedback(created_at DESC);


-- Module: blog, File: 201_20260313_indexes.sql
-- ---------------------------
-- MODULE NAME: Blog System Indexes
-- MODULE DATE: 20260313
-- MODULE SCOPE: Indexes
-- ---------------------------



-- ---------------------------
-- Blog Posts Indexes
-- ---------------------------
CREATE INDEX IF NOT EXISTS idx_blog_posts_user_id ON public.blog_posts(user_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_topic_id ON public.blog_posts(topic_id);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON public.blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_created_at ON public.blog_posts(created_at);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON public.blog_posts(published_at);
CREATE INDEX IF NOT EXISTS idx_blog_posts_is_featured ON public.blog_posts(is_featured) WHERE is_featured = true;
CREATE INDEX IF NOT EXISTS idx_blog_posts_is_sponsored ON public.blog_posts(is_sponsored) WHERE is_sponsored = true;
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON public.blog_posts(is_admin_approved, is_user_published);

-- ---------------------------
-- Blog Topics Indexes
-- ---------------------------
CREATE INDEX IF NOT EXISTS idx_blog_topics_slug ON public.blog_topics(slug);
CREATE INDEX IF NOT EXISTS idx_blog_topics_parent_id ON public.blog_topics(parent_id);

-- ---------------------------
-- Blog Comments Indexes
-- ---------------------------
CREATE INDEX IF NOT EXISTS idx_blog_comments_post_id ON public.blog_comments(post_id);
CREATE INDEX IF NOT EXISTS idx_blog_comments_user_id ON public.blog_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_blog_comments_parent_id ON public.blog_comments(parent_id);
CREATE INDEX IF NOT EXISTS idx_blog_comments_created_at ON public.blog_comments(created_at);

-- ---------------------------
-- Blog Activities Indexes
-- ---------------------------
CREATE INDEX IF NOT EXISTS idx_blog_activities_post_id ON public.blog_activities(post_id);
CREATE INDEX IF NOT EXISTS idx_blog_activities_user_id ON public.blog_activities(user_id);
CREATE INDEX IF NOT EXISTS idx_blog_activities_type ON public.blog_activities(activity_type);
CREATE INDEX IF NOT EXISTS idx_blog_activities_created_at ON public.blog_activities(created_at);


-- Module: user-management, File: 300_20260227_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: User Management
-- MODULE DATE: 20260227
-- MODULE SCOPE: RLS & Grants
-- ---------------------------



-- ---------------------------
-- Helper: check super admin (bypasses RLS; used by config and other modules)
-- ---------------------------

CREATE OR REPLACE FUNCTION public.is_super_admin(user_auth_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    is_admin BOOLEAN;
BEGIN
    SELECT is_super_admin INTO is_admin
    FROM public.users
    WHERE auth_id = user_auth_id
    LIMIT 1;
    RETURN COALESCE(is_admin, false);
END;
$$;

GRANT EXECUTE ON FUNCTION public.is_super_admin(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin(UUID) TO anon;
COMMENT ON FUNCTION public.is_super_admin(UUID) IS 'Check if a user is a super admin (bypasses RLS to avoid recursion)';

-- ---------------------------
-- Users
-- ---------------------------

-- Anon: public profile columns only (no verification tokens)
GRANT SELECT (id, full_name, email, is_email_verified, is_super_admin, created_at, updated_at) ON public.users TO anon;

-- Authenticated: full access (restricted by RLS)
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.users TO authenticated;
GRANT SELECT (email_verification_token, email_verification_token_expires) ON public.users TO authenticated;

-- Service role
GRANT DELETE, INSERT, REFERENCES, SELECT, TRUNCATE, UPDATE, TRIGGER ON public.users TO service_role;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated users can view their own data" ON public.users;
CREATE POLICY "Authenticated users can view their own data"
ON public.users
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (auth_id = auth.uid());

DROP POLICY IF EXISTS "Owners can update their profiles" ON public.users;
CREATE POLICY "Owners can update their profiles"
ON public.users
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (auth_id = auth.uid())
WITH CHECK (auth_id = auth.uid());

DROP POLICY IF EXISTS "Anon users can view public profiles" ON public.users;
CREATE POLICY "Anon users can view public profiles"
ON public.users
AS PERMISSIVE
FOR SELECT
TO anon
USING (true);

-- Super admins can view and update any user (e.g. for admin tooling)
DROP POLICY IF EXISTS "Super admins can update any user data" ON public.users;
CREATE POLICY "Super admins can update any user data"
ON public.users
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (public.is_super_admin(auth.uid()))
WITH CHECK (public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS "Super admins can view all user data" ON public.users;
CREATE POLICY "Super admins can view all user data"
ON public.users
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (public.is_super_admin(auth.uid()));

-- ---------------------------
-- User Profiles
-- ---------------------------

GRANT SELECT ON public.user_profiles TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.user_profiles TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRUNCATE, UPDATE, TRIGGER ON public.user_profiles TO service_role;

ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "User profiles are publicly accessible" ON public.user_profiles;
CREATE POLICY "User profiles are publicly accessible"
ON public.user_profiles
AS PERMISSIVE
FOR SELECT
TO public
USING (true);

DROP POLICY IF EXISTS "Owners can update their own profiles" ON public.user_profiles;
CREATE POLICY "Owners can update their own profiles"
ON public.user_profiles
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users
        WHERE users.id = user_profiles.owner_id
        AND users.auth_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.users
        WHERE users.id = user_profiles.owner_id
        AND users.auth_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Owners can insert their own profiles" ON public.user_profiles;
CREATE POLICY "Owners can insert their own profiles"
ON public.user_profiles
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.users
        WHERE users.id = user_profiles.owner_id
        AND users.auth_id = auth.uid()
    )
);

DROP POLICY IF EXISTS "Super admins can manage any profile" ON public.user_profiles;
CREATE POLICY "Super admins can manage any profile"
ON public.user_profiles
AS PERMISSIVE
FOR ALL
TO authenticated
USING (public.is_super_admin(auth.uid()))
WITH CHECK (public.is_super_admin(auth.uid()));

-- ---------------------------
-- Avatars (storage.objects for bucket 'avatars')
-- ---------------------------

GRANT SELECT ON storage.objects TO anon;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRUNCATE, UPDATE, TRIGGER ON storage.objects TO authenticated;
GRANT DELETE, INSERT, REFERENCES, SELECT, TRUNCATE, UPDATE, TRIGGER ON storage.objects TO service_role;

DROP POLICY IF EXISTS "Allow authenticated users to upload their own avatar." ON storage.objects;
CREATE POLICY "Allow authenticated users to upload their own avatar."
ON storage.objects
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'avatars'::text
    AND auth.uid() = owner
);

DROP POLICY IF EXISTS "Allow authenticated users to update their own avatar." ON storage.objects;
CREATE POLICY "Allow authenticated users to update their own avatar."
ON storage.objects
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'avatars'::text
    AND auth.uid() = owner
)
WITH CHECK (
    bucket_id = 'avatars'::text
    AND auth.uid() = owner
);

DROP POLICY IF EXISTS "Allow admin users to delete their own avatar." ON storage.objects;
CREATE POLICY "Allow admin users to delete their own avatar."
ON storage.objects
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (
    bucket_id = 'avatars'::text
    AND auth.uid() = owner
);

DROP POLICY IF EXISTS "Avatar images are publicly accessible." ON storage.objects;
CREATE POLICY "Avatar images are publicly accessible."
ON storage.objects
AS PERMISSIVE
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'avatars'::text);

DROP POLICY IF EXISTS "Allow service_role to manage avatars" ON storage.objects;
CREATE POLICY "Allow service_role to manage avatars"
ON storage.objects
AS PERMISSIVE
FOR ALL
TO service_role
USING (bucket_id = 'avatars'::text);

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: user-auth, File: 301_20260227_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: User Auth
-- MODULE DATE: 20260227
-- MODULE SCOPE: RLS & Grants
-- ---------------------------



-- ---------------------------
-- refresh_tokens RLS
-- ---------------------------

ALTER TABLE public.refresh_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own refresh tokens" ON public.refresh_tokens;
CREATE POLICY "Users can view their own refresh tokens"
ON public.refresh_tokens
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can revoke their own refresh tokens" ON public.refresh_tokens;
CREATE POLICY "Users can revoke their own refresh tokens"
ON public.refresh_tokens
FOR UPDATE
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can insert their own refresh tokens" ON public.refresh_tokens;
CREATE POLICY "Users can insert their own refresh tokens"
ON public.refresh_tokens
FOR INSERT
WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Service roles can manage refresh tokens" ON public.refresh_tokens;
CREATE POLICY "Service roles can manage refresh tokens"
ON public.refresh_tokens
FOR ALL
USING (auth.role() = 'service_role');

-- ---------------------------
-- Comments
-- ---------------------------

COMMENT ON TABLE public.refresh_tokens IS 'Stores refresh tokens for JWT authentication';
COMMENT ON COLUMN public.refresh_tokens.id IS 'Unique identifier for the refresh token record';
COMMENT ON COLUMN public.refresh_tokens.user_id IS 'Reference to the user this token belongs to';
COMMENT ON COLUMN public.refresh_tokens.token IS 'The actual refresh token (hashed)';
COMMENT ON COLUMN public.refresh_tokens.created_at IS 'When the token was created';
COMMENT ON COLUMN public.refresh_tokens.expires_at IS 'When the token expires';
COMMENT ON COLUMN public.refresh_tokens.revoked IS 'Whether the token has been revoked';
COMMENT ON COLUMN public.refresh_tokens.revoked_at IS 'When the token was revoked, if applicable';
COMMENT ON COLUMN public.refresh_tokens.replaced_by IS 'Reference to the token that replaced this one (token rotation)';
COMMENT ON COLUMN public.refresh_tokens.ip_address IS 'IP address where the token was issued';
COMMENT ON COLUMN public.refresh_tokens.user_agent IS 'Browser/device information where the token was issued';

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: organization, File: 301_20260309_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: Organization
-- MODULE DATE: 20260309
-- MODULE SCOPE: RLS & Grants
-- ---------------------------



-- ---------------------------
-- Grants
-- ---------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON public.organizations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_organizations TO authenticated;
GRANT USAGE ON TYPE public.workspace_membership_role TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.organizations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_organizations TO service_role;

GRANT SELECT, INSERT, DELETE ON public.organization_invites TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.organization_invites TO service_role;

-- ---------------------------
-- RLS: organizations
-- ---------------------------

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;

-- Users can view organizations they are a member of
DROP POLICY IF EXISTS "Members can view organization" ON public.organizations;
CREATE POLICY "Members can view organization"
ON public.organizations
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_organizations uo
        JOIN public.users u ON u.id = uo.user_id
        WHERE uo.organization_id = organizations.id
          AND u.auth_id = auth.uid()
          AND (uo.disabled = FALSE)
    )
);

-- Only org members with admin or superadmin can update
DROP POLICY IF EXISTS "Admins can update organization" ON public.organizations;
CREATE POLICY "Admins can update organization"
ON public.organizations
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_organizations uo
        JOIN public.users u ON u.id = uo.user_id
        WHERE uo.organization_id = organizations.id
          AND u.auth_id = auth.uid()
          AND (uo.disabled = FALSE)
          AND uo.role IN ('admin', 'superadmin')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_organizations uo
        JOIN public.users u ON u.id = uo.user_id
        WHERE uo.organization_id = organizations.id
          AND u.auth_id = auth.uid()
          AND (uo.disabled = FALSE)
          AND uo.role IN ('admin', 'superadmin')
    )
);

-- Authenticated users can create organizations (membership is added in app layer)
DROP POLICY IF EXISTS "Authenticated can create organization" ON public.organizations;
CREATE POLICY "Authenticated can create organization"
ON public.organizations
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Only superadmin members can delete (optional; we may disallow delete in app)
DROP POLICY IF EXISTS "Superadmin can delete organization" ON public.organizations;
CREATE POLICY "Superadmin can delete organization"
ON public.organizations
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_organizations uo
        JOIN public.users u ON u.id = uo.user_id
        WHERE uo.organization_id = organizations.id
          AND u.auth_id = auth.uid()
          AND (uo.disabled = FALSE)
          AND uo.role = 'superadmin'
    )
);

-- ---------------------------
-- RLS: user_organizations
-- ---------------------------

ALTER TABLE public.user_organizations ENABLE ROW LEVEL SECURITY;

-- Members can view memberships of their organizations
DROP POLICY IF EXISTS "Members can view user_organizations" ON public.user_organizations;
CREATE POLICY "Members can view user_organizations"
ON public.user_organizations
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_organizations self
        JOIN public.users u ON u.id = self.user_id
        WHERE self.organization_id = user_organizations.organization_id
          AND u.auth_id = auth.uid()
          AND (self.disabled = FALSE)
    )
);

-- Admins/superadmins can insert (add member) into user_organizations
DROP POLICY IF EXISTS "Admins can add team member" ON public.user_organizations;
CREATE POLICY "Admins can add team member"
ON public.user_organizations
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_organizations self
        JOIN public.users u ON u.id = self.user_id
        WHERE self.organization_id = user_organizations.organization_id
          AND u.auth_id = auth.uid()
          AND (self.disabled = FALSE)
          AND self.role IN ('admin', 'superadmin')
    )
);

-- Admins can update (e.g. role, disabled) for non-superadmin members; users can update own disabled
DROP POLICY IF EXISTS "Admins can update membership" ON public.user_organizations;
CREATE POLICY "Admins can update membership"
ON public.user_organizations
AS PERMISSIVE
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.user_organizations self
        JOIN public.users u ON u.id = self.user_id
        WHERE self.organization_id = user_organizations.organization_id
          AND u.auth_id = auth.uid()
          AND (self.disabled = FALSE)
          AND self.role IN ('admin', 'superadmin')
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_organizations self
        JOIN public.users u ON u.id = self.user_id
        WHERE self.organization_id = user_organizations.organization_id
          AND u.auth_id = auth.uid()
          AND (self.disabled = FALSE)
          AND self.role IN ('admin', 'superadmin')
    )
);

-- Admins can delete (remove member) other members; users can delete own membership
DROP POLICY IF EXISTS "Admins or self can delete membership" ON public.user_organizations;
CREATE POLICY "Admins or self can delete membership"
ON public.user_organizations
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.id = user_organizations.user_id AND u.auth_id = auth.uid()
    )
    OR EXISTS (
        SELECT 1 FROM public.user_organizations self
        JOIN public.users u ON u.id = self.user_id
        WHERE self.organization_id = user_organizations.organization_id
          AND u.auth_id = auth.uid()
          AND (self.disabled = FALSE)
          AND self.role IN ('admin', 'superadmin')
    )
);

-- ---------------------------
-- RLS: organization_invites
-- ---------------------------

ALTER TABLE public.organization_invites ENABLE ROW LEVEL SECURITY;

-- Invitee can see invites sent to their email
DROP POLICY IF EXISTS "Invitee can view own invites" ON public.organization_invites;
CREATE POLICY "Invitee can view own invites"
ON public.organization_invites
AS PERMISSIVE
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
          AND LOWER(u.email) = LOWER(organization_invites.email)
    )
);

-- Admins/superadmins of the org can create invites (send invitation)
DROP POLICY IF EXISTS "Admins can create invite" ON public.organization_invites;
CREATE POLICY "Admins can create invite"
ON public.organization_invites
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.user_organizations uo
        JOIN public.users u ON u.id = uo.user_id
        WHERE uo.organization_id = organization_invites.organization_id
          AND u.auth_id = auth.uid()
          AND (uo.disabled = FALSE)
          AND uo.role IN ('admin', 'superadmin')
    )
);

-- Invitee can delete their own invite (e.g. when accepting)
DROP POLICY IF EXISTS "Invitee can delete own invite" ON public.organization_invites;
CREATE POLICY "Invitee can delete own invite"
ON public.organization_invites
AS PERMISSIVE
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.auth_id = auth.uid()
          AND LOWER(u.email) = LOWER(organization_invites.email)
    )
);

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: rbac, File: 302_20260311_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: RBAC
-- MODULE DATE: 20260311
-- MODULE SCOPE: RLS & Grants
-- ---------------------------
-- Runs after user-management/301 so public.is_super_admin(uuid) exists.
-- content-os: public.users.id is PK; users.auth_id = auth.uid() for current user.



GRANT USAGE ON TYPE public.app_role TO authenticated;
GRANT USAGE ON TYPE public.app_permission TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.role_permissions TO authenticated;

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- Users can view their own roles (via public.users.id from auth_id)
DROP POLICY IF EXISTS "Users can view their own roles" ON public.user_roles;
CREATE POLICY "Users can view their own roles"
    ON public.user_roles FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.users u
            WHERE u.id = user_roles.user_id AND u.auth_id = auth.uid()
        )
    );

-- Super admins can view all roles
DROP POLICY IF EXISTS "Super admins can view all roles" ON public.user_roles;
CREATE POLICY "Super admins can view all roles"
    ON public.user_roles FOR SELECT TO authenticated
    USING (public.is_super_admin(auth.uid()));

-- Only super admins can insert/update/delete user_roles (assign/remove via RPC in app)
DROP POLICY IF EXISTS "Super admins can insert roles" ON public.user_roles;
CREATE POLICY "Super admins can insert roles"
    ON public.user_roles FOR INSERT TO authenticated
    WITH CHECK (public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS "Super admins can update roles" ON public.user_roles;
CREATE POLICY "Super admins can update roles"
    ON public.user_roles FOR UPDATE TO authenticated
    USING (public.is_super_admin(auth.uid()))
    WITH CHECK (public.is_super_admin(auth.uid()));

DROP POLICY IF EXISTS "Super admins can delete roles" ON public.user_roles;
CREATE POLICY "Super admins can delete roles"
    ON public.user_roles FOR DELETE TO authenticated
    USING (public.is_super_admin(auth.uid()));

-- Authenticated can read role_permissions
DROP POLICY IF EXISTS "Authenticated can view role permissions" ON public.role_permissions;
CREATE POLICY "Authenticated can view role permissions"
    ON public.role_permissions FOR SELECT TO authenticated
    USING (true);

-- Only super admins can modify role_permissions
DROP POLICY IF EXISTS "Super admins can manage role permissions" ON public.role_permissions;
CREATE POLICY "Super admins can manage role permissions"
    ON public.role_permissions FOR ALL TO authenticated
    USING (public.is_super_admin(auth.uid()))
    WITH CHECK (public.is_super_admin(auth.uid()));


-- Module: config, File: 302_20260311_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: ADMIN AREA
-- MODULE DATE: 20260311
-- MODULE SCOPE: RLS & Grants
-- ---------------------------
-- Runs after user-management/301 so public.is_super_admin(uuid) exists.
-- ---------------------------



-- ---------------------------
-- ADMIN MODULE CONFIGURATION
-- ---------------------------

-- Enable Row-Level Security on the module_configs table
ALTER TABLE public.module_configs ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users to read (SELECT) configs
-- If you want *everyone* including non-authenticated to read, remove auth checks.
CREATE POLICY "Allow all to read module configs"
ON public.module_configs
FOR SELECT
USING (true);

-- Allow only super admins to INSERT new configs
DROP POLICY IF EXISTS "Allow admins to insert module configs" ON public.module_configs;
CREATE POLICY "Allow admins to insert module configs"
ON public.module_configs
FOR INSERT
WITH CHECK (public.is_super_admin(auth.uid()));

-- Allow only super admins to UPDATE configs
DROP POLICY IF EXISTS "Allow admins to update module configs" ON public.module_configs;
CREATE POLICY "Allow admins to update module configs"
ON public.module_configs
FOR UPDATE
USING (public.is_super_admin(auth.uid()));

-- Allow only super admins to DELETE configs
DROP POLICY IF EXISTS "Allow admins to delete module configs" ON public.module_configs;
CREATE POLICY "Allow admins to delete module configs"
ON public.module_configs
FOR DELETE
USING (public.is_super_admin(auth.uid()));

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: feedback, File: 302_20260311_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: Feedback
-- MODULE DATE: 20260311
-- MODULE SCOPE: RLS & Grants
-- ---------------------------
-- Runs after user-management/300 so public.is_super_admin(uuid) exists.
-- Anyone can insert. Select/update/delete: super_admin or user with admin/support app role (support handles feedback; editor is blog-only).



GRANT SELECT, INSERT ON public.feedback TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.feedback TO service_role;

ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Anyone can insert feedback
DROP POLICY IF EXISTS "Anyone can insert feedback" ON public.feedback;
CREATE POLICY "Anyone can insert feedback"
    ON public.feedback FOR INSERT TO anon, authenticated
    WITH CHECK (true);

-- Super admin, admins and support can select
DROP POLICY IF EXISTS "Super admin admins support can select feedback" ON public.feedback;
CREATE POLICY "Super admin admins support can select feedback"
    ON public.feedback FOR SELECT TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'support')
        )
    );

-- Super admin, admins and support can update
DROP POLICY IF EXISTS "Super admin admins support can update feedback" ON public.feedback;
CREATE POLICY "Super admin admins support can update feedback"
    ON public.feedback FOR UPDATE TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'support')
        )
    );

-- Super admin, admins and support can delete
DROP POLICY IF EXISTS "Super admin admins support can delete feedback" ON public.feedback;
CREATE POLICY "Super admin admins support can delete feedback"
    ON public.feedback FOR DELETE TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'support')
        )
    );


-- Module: blog, File: 302_20260313_rlsgrants.sql
-- ---------------------------
-- MODULE NAME: Blog System RLS and Grants
-- MODULE DATE: 20260313
-- MODULE SCOPE: Row Level Security and Grants
-- ---------------------------



-- ---------------------------
-- Enable Row Level Security
-- ---------------------------
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blog_activities ENABLE ROW LEVEL SECURITY;

-- ---------------------------
-- Blog Posts Policies
-- ---------------------------

-- Public (including anon) can view only published and approved posts
DROP POLICY IF EXISTS "Public can view published posts" ON public.blog_posts;
CREATE POLICY "Public can view published posts" ON public.blog_posts
    FOR SELECT TO anon, authenticated USING (is_admin_approved = true AND is_user_published = true);

-- Authors can manage (select/update/delete) their own posts
DROP POLICY IF EXISTS "Authors can manage their own posts" ON public.blog_posts;
CREATE POLICY "Authors can manage their own posts" ON public.blog_posts
    FOR ALL TO authenticated USING (
        user_id = (
            SELECT id FROM public.users WHERE auth_id = auth.uid()
        )
    )
    WITH CHECK (
        user_id = (
            SELECT id FROM public.users WHERE auth_id = auth.uid()
        )
    );

-- Super admin, admins and editors can manage all posts
DROP POLICY IF EXISTS "Super admin admins editors can manage all posts" ON public.blog_posts;
CREATE POLICY "Super admin admins editors can manage all posts" ON public.blog_posts
    FOR ALL TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    )
    WITH CHECK (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    );

-- ---------------------------
-- Blog Topics Policies
-- ---------------------------

DROP POLICY IF EXISTS "Everyone can view topics" ON public.blog_topics;
CREATE POLICY "Everyone can view topics" ON public.blog_topics
    FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Super admin admins editors can manage topics" ON public.blog_topics;
CREATE POLICY "Super admin admins editors can manage topics" ON public.blog_topics
    FOR ALL TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    )
    WITH CHECK (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    );

-- ---------------------------
-- Blog Comments Policies
-- ---------------------------

DROP POLICY IF EXISTS "Everyone can view approved comments" ON public.blog_comments;
CREATE POLICY "Everyone can view approved comments" ON public.blog_comments
    FOR SELECT TO anon, authenticated USING (is_approved = true);

DROP POLICY IF EXISTS "Users can manage their own comments" ON public.blog_comments;
CREATE POLICY "Users can manage their own comments" ON public.blog_comments
    FOR ALL TO authenticated
    USING (
        user_id = (
            SELECT id FROM public.users WHERE auth_id = auth.uid()
        )
    )
    WITH CHECK (
        user_id = (
            SELECT id FROM public.users WHERE auth_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "Super admin admins editors can manage comments" ON public.blog_comments;
CREATE POLICY "Super admin admins editors can manage comments" ON public.blog_comments
    FOR ALL TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    )
    WITH CHECK (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    );

-- ---------------------------
-- Blog Activities Policies
-- ---------------------------

DROP POLICY IF EXISTS "Users can view their own activities" ON public.blog_activities;
CREATE POLICY "Users can view their own activities" ON public.blog_activities
    FOR SELECT TO authenticated
    USING (
        user_id = (
            SELECT id FROM public.users WHERE auth_id = auth.uid()
        )
    );

DROP POLICY IF EXISTS "System can insert activities" ON public.blog_activities;
CREATE POLICY "System can insert activities" ON public.blog_activities
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Super admin admins editors can view all activities" ON public.blog_activities;
CREATE POLICY "Super admin admins editors can view all activities" ON public.blog_activities
    FOR ALL TO authenticated
    USING (
        public.is_super_admin(auth.uid())
        OR EXISTS (
            SELECT 1 FROM public.users u
            JOIN public.user_roles ur ON ur.user_id = u.id
            WHERE u.auth_id = auth.uid() AND ur.role IN ('admin', 'editor')
        )
    );

-- ---------------------------
-- Blog Images Storage Policies
-- ---------------------------
CREATE POLICY "Allow authenticated users to delete their blog images" 
    ON storage.objects
    AS PERMISSIVE
    FOR DELETE
    TO authenticated
    USING (
        bucket_id = 'blog_images'::text
        AND auth.role() = 'authenticated'::text
        AND auth.uid() = owner
    );

CREATE POLICY "Allow authenticated users to update their blog images" 
    ON storage.objects
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated
    USING (
        bucket_id = 'blog_images'::text
        AND auth.role() = 'authenticated'::text
        AND auth.uid() = owner
    );

CREATE POLICY "Allow authenticated users to upload blog images" 
    ON storage.objects
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK (
        bucket_id = 'blog_images'::text
        AND auth.role() = 'authenticated'::text
    );

CREATE POLICY "Allow read access to blog images"
    ON storage.objects
    AS PERMISSIVE
    FOR SELECT
    TO anon, authenticated
    USING (
        bucket_id = 'blog_images'::text
    );

CREATE POLICY "Allow service_role to manage blog images" 
    ON storage.objects
    AS PERMISSIVE
    FOR ALL
    TO service_role
    USING (bucket_id = 'blog_images'::text);

-- ---------------------------
-- Grants
-- ---------------------------
-- Anonymous users
GRANT SELECT ON public.blog_posts TO anon;
GRANT SELECT ON public.blog_topics TO anon;
GRANT SELECT ON public.blog_comments TO anon;
GRANT SELECT ON storage.objects TO anon;

-- Authenticated users
GRANT ALL ON public.blog_posts TO authenticated;
GRANT SELECT ON public.blog_topics TO authenticated;
GRANT ALL ON public.blog_comments TO authenticated;
GRANT INSERT ON public.blog_activities TO authenticated;
GRANT DELETE, INSERT, SELECT, UPDATE ON storage.objects TO authenticated;

-- Service role (for backend operations)
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON storage.objects TO service_role;

-- ---------------------------
-- Helper Functions
-- ---------------------------

-- Function to get all users who have published blog posts (profile fields from user_profiles)
CREATE OR REPLACE FUNCTION public.get_published_blog_authors()
RETURNS TABLE (
    id UUID,
    full_name TEXT,
    username TEXT,
    avatar_url TEXT,
    website TEXT,
    tag_line TEXT,
    post_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT
        u.id,
        u.full_name,
        NULL::TEXT AS username,
        up.avatar_url,
        up.website_url AS website,
        up.tag_line,
        COUNT(bp.id) OVER (PARTITION BY u.id) AS post_count
    FROM
        public.users u
        INNER JOIN public.blog_posts bp ON u.id = bp.user_id
        LEFT JOIN public.user_profiles up ON up.owner_id = u.id
    WHERE
        bp.is_user_published = true
        AND bp.is_admin_approved = true
    ORDER BY
        post_count DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get all active blog topics (topics that have published posts)
CREATE OR REPLACE FUNCTION public.get_active_blog_topics()
RETURNS TABLE (
    id UUID,
    name TEXT,
    slug TEXT,
    description TEXT,
    parent_id UUID,
    post_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT
        bt.id,
        bt.name,
        bt.slug,
        bt.description,
        bt.parent_id,
        COUNT(bp.id) OVER (PARTITION BY bt.id) as post_count
    FROM
        public.blog_topics bt
        INNER JOIN public.blog_posts bp ON bt.id = bp.topic_id
    WHERE
        bp.is_user_published = true
        AND bp.is_admin_approved = true
    ORDER BY
        post_count DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Module: user-management, File: 400_20260227_functions.sql
-- ---------------------------
-- MODULE NAME: User Management
-- MODULE DATE: 20260227
-- MODULE SCOPE: Functions
-- ---------------------------



-- ---------------------------
-- (No module-specific functions; handle_new_user lives in user-auth)
-- ---------------------------

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: user-auth, File: 401_20260227_functions.sql
-- ---------------------------
-- MODULE NAME: User Auth
-- MODULE DATE: 20260227
-- MODULE SCOPE: Functions
-- ---------------------------



-- ---------------------------
-- Sync auth.users -> public.users
-- ---------------------------

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.users (id, auth_id, email, full_name)
  VALUES (
    new.id,
    new.id,
    new.email,
    COALESCE((new.raw_user_meta_data->>'full_name')::text, new.email)
  );
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: rbac, File: 401_20260311_functions.sql
-- ---------------------------
-- MODULE NAME: RBAC (Role-Based Access Control)
-- MODULE DATE: 20260311
-- MODULE SCOPE: Functions
-- ---------------------------
-- user_id in user_roles is public.users.id. auth.uid() is Supabase auth user id.

-- Function to get all permissions for a user (by public.users.id)
CREATE OR REPLACE FUNCTION public.get_user_permissions(user_uuid UUID)
RETURNS TABLE (permission public.app_permission) AS $$
BEGIN
    RETURN QUERY
    SELECT DISTINCT rp.permission
    FROM public.user_roles ur
    JOIN public.role_permissions rp ON ur.role = rp.role
    WHERE ur.user_id = user_uuid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

COMMENT ON FUNCTION public.get_user_permissions(UUID) IS 'Returns all permissions for a given user (public.users.id) based on their roles';

-- Function to check if user has a specific role (by public.users.id)
CREATE OR REPLACE FUNCTION public.has_role(user_uuid UUID, check_role public.app_role)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS(
        SELECT 1 FROM public.user_roles
        WHERE user_id = user_uuid AND role = check_role
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

COMMENT ON FUNCTION public.has_role(UUID, public.app_role) IS 'Check if a user (public.users.id) has a specific role';

-- Function to assign a role to a user. assigned_by_user_id is public.users.id.
CREATE OR REPLACE FUNCTION public.assign_user_role(
    target_user_id UUID,
    role_to_assign public.app_role,
    assigned_by_user_id UUID
)
RETURNS UUID AS $$
DECLARE
    new_role_id UUID;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.id = assigned_by_user_id
        AND (u.is_super_admin = true OR EXISTS(
            SELECT 1 FROM public.user_roles ur
            WHERE ur.user_id = assigned_by_user_id AND ur.role = 'admin'
        ))
    ) THEN
        RAISE EXCEPTION 'Only admins can assign roles';
    END IF;

    INSERT INTO public.user_roles (user_id, role, created_by)
    VALUES (target_user_id, role_to_assign, assigned_by_user_id)
    ON CONFLICT (user_id, role) DO NOTHING
    RETURNING id INTO new_role_id;

    RETURN new_role_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

COMMENT ON FUNCTION public.assign_user_role(UUID, public.app_role, UUID) IS 'Assigns a role to a user. Caller must be super admin or have admin role.';

-- Function to remove a role from a user
CREATE OR REPLACE FUNCTION public.remove_user_role(
    target_user_id UUID,
    role_to_remove public.app_role,
    removed_by_user_id UUID
)
RETURNS BOOLEAN AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM public.users u
        WHERE u.id = removed_by_user_id
        AND (u.is_super_admin = true OR EXISTS(
            SELECT 1 FROM public.user_roles ur
            WHERE ur.user_id = removed_by_user_id AND ur.role = 'admin'
        ))
    ) THEN
        RAISE EXCEPTION 'Only admins can remove roles';
    END IF;

    DELETE FROM public.user_roles
    WHERE user_id = target_user_id AND role = role_to_remove;

    RETURN true;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = '';

COMMENT ON FUNCTION public.remove_user_role(UUID, public.app_role, UUID) IS 'Removes a role from a user. Caller must be super admin or have admin role.';

-- Grant execute to authenticated (must run after functions exist)
GRANT EXECUTE ON FUNCTION public.get_user_permissions(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(UUID, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.assign_user_role(UUID, public.app_role, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.remove_user_role(UUID, public.app_role, UUID) TO authenticated;

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: blog, File: 401_20260313_functions.sql
-- ---------------------------
-- MODULE NAME: Blog System Functions
-- MODULE DATE: 20260313
-- MODULE SCOPE: Functions
-- ---------------------------



-- ---------------------------
-- Update Updated At Function
-- ---------------------------
CREATE OR REPLACE FUNCTION public.update_blog_updated_at_column()
RETURNS TRIGGER 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply to all tables with updated_at
CREATE TRIGGER update_blog_posts_updated_at
    BEFORE UPDATE ON public.blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION public.update_blog_updated_at_column();

CREATE TRIGGER update_blog_topics_updated_at
    BEFORE UPDATE ON public.blog_topics
    FOR EACH ROW
    EXECUTE FUNCTION public.update_blog_updated_at_column();

CREATE TRIGGER update_blog_comments_updated_at
    BEFORE UPDATE ON public.blog_comments
    FOR EACH ROW
    EXECUTE FUNCTION public.update_blog_updated_at_column();

-- ---------------------------
-- Slug Generation
-- ---------------------------
CREATE OR REPLACE FUNCTION public.generate_unique_slug(title TEXT, table_name TEXT)
RETURNS TEXT
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    base_slug TEXT;
    new_slug TEXT;
    counter INTEGER := 1;
    slug_exists BOOLEAN;
BEGIN
    -- Convert title to lowercase and replace spaces and special chars with hyphens
    base_slug := lower(regexp_replace(title, '[^a-zA-Z0-9\\s]', '', 'g'));
    base_slug := regexp_replace(base_slug, '\\s+', '-', 'g');
    new_slug := base_slug;
    
    -- Check if slug exists in the specified table
    LOOP
        EXECUTE format('SELECT EXISTS(SELECT 1 FROM %I WHERE slug = $1)', table_name)
        INTO slug_exists
        USING new_slug;
        
        EXIT WHEN NOT slug_exists;
        
        counter := counter + 1;
        new_slug := base_slug || '-' || counter::text;
    END LOOP;
    
    RETURN new_slug;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------
-- Auto-generate Slugs
-- ---------------------------
CREATE OR REPLACE FUNCTION public.generate_post_slug()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.slug IS NULL THEN
        NEW.slug := public.generate_unique_slug(NEW.title, 'blog_posts');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_post_slug
    BEFORE INSERT ON public.blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION public.generate_post_slug();

CREATE OR REPLACE FUNCTION public.generate_topic_slug()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.slug IS NULL THEN
        NEW.slug := public.generate_unique_slug(NEW.name, 'blog_topics');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_topic_slug
    BEFORE INSERT ON public.blog_topics
    FOR EACH ROW
    EXECUTE FUNCTION public.generate_topic_slug();

-- ---------------------------
-- Reading Time Calculation
-- ---------------------------
CREATE OR REPLACE FUNCTION public.calculate_blog_reading_time()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    words_per_minute INTEGER := 200;
    word_count INTEGER;
BEGIN
    -- Count words in content (rough estimate)
    word_count := array_length(regexp_split_to_array(NEW.content, '\\s+'), 1);
    
    -- Calculate reading time in minutes (rounded up)
    NEW.reading_time_minutes := CEILING(word_count::float / words_per_minute);
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_reading_time
    BEFORE INSERT OR UPDATE OF content ON public.blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION public.calculate_blog_reading_time();

-- ---------------------------
-- Update Published At
-- ---------------------------
CREATE OR REPLACE FUNCTION public.update_blog_published_at()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.is_admin_approved AND NEW.is_user_published AND OLD.published_at IS NULL THEN
        NEW.published_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_published_at
    BEFORE UPDATE ON public.blog_posts
    FOR EACH ROW
    EXECUTE FUNCTION public.update_blog_published_at();

-- ---------------------------
-- Update View Count
-- ---------------------------
CREATE OR REPLACE FUNCTION public.increment_blog_view_count()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF NEW.activity_type = 'view' THEN
        UPDATE public.blog_posts
        SET view_count = view_count + 1
        WHERE id = NEW.post_id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_post_view_count
    AFTER INSERT ON public.blog_activities
    FOR EACH ROW
    EXECUTE FUNCTION public.increment_blog_view_count();

-- ---------------------------
-- Update Like Count
-- ---------------------------
CREATE OR REPLACE FUNCTION public.update_blog_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT' AND NEW.activity_type = 'like') THEN
    UPDATE public.blog_posts
    SET like_count = like_count + 1
    WHERE id = NEW.post_id;
  ELSIF (TG_OP = 'DELETE' AND OLD.activity_type = 'like') THEN
    UPDATE public.blog_posts
    SET like_count = GREATEST(like_count - 1, 0)
    WHERE id = OLD.post_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_blog_post_like_count_trigger ON public.blog_activities;
CREATE TRIGGER update_blog_post_like_count_trigger
  AFTER INSERT OR DELETE ON public.blog_activities
  FOR EACH ROW
  EXECUTE FUNCTION public.update_blog_post_like_count();


-- Module: user-management, File: 500_20260227_seed.sql
-- ---------------------------
-- MODULE NAME: User Management
-- MODULE DATE: 20260227
-- MODULE SCOPE: Seed
-- ---------------------------



-- ---------------------------
-- Avatars
-- ---------------------------

INSERT INTO storage.buckets (
    id, 
    name, 
    owner, 
    created_at, 
    updated_at, 
    public, 
    avif_autodetection, 
    file_size_limit, 
    allowed_mime_types, 
    owner_id
) VALUES (
    'avatars', 
    'avatars', 
    NULL, 
    '2024-05-15 17:15:33.949923+00', 
    '2024-05-15 17:15:33.949923+00', 
    TRUE, 
    FALSE, 
    NULL, 
    NULL, 
    NULL
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: user-auth, File: 501_20260227_seed.sql
-- ---------------------------
-- MODULE NAME: User Auth
-- MODULE DATE: 20260227
-- MODULE SCOPE: Seed
-- ---------------------------



-- ---------------------------
-- User Auth Config (optional: ensure module_configs exists)
-- ---------------------------


INSERT INTO public.module_configs (module_name, config) VALUES
('user_auth', '{
  "ALLOW_USER_SIGNUPS": "true"
}'::jsonb);


-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: rbac, File: 501_20260311_seed.sql
-- ---------------------------
-- MODULE NAME: RBAC
-- MODULE DATE: 20260311
-- MODULE SCOPE: Seed
-- ---------------------------

-- Admin: can assign/remove roles and manage role-permission mapping
INSERT INTO public.role_permissions (role, permission) VALUES
    ('admin', 'users.manage_roles')
ON CONFLICT (role, permission) DO NOTHING;


-- Module: config, File: 501_20260311_seed.sql
-- ---------------------------
-- MODULE NAME: config
-- MODULE DATE: 20260311
-- MODULE SCOPE: Seed
-- ---------------------------



-- ---------------------------
-- Company Information Config
-- ---------------------------

INSERT INTO public.module_configs (module_name, config) VALUES
('company_information', '{
  "NAME": "Content OS",
  "LEGAL_NAME": "Content OS",
  "VAT_ID": "",
  "COMPANY_ADDRESS": "",
  "URL": "https://example.com",
  "SUPPORT_EMAIL": "support@example.com",
  "SUPPORT_PHONE": "",
  "FOUNDING_YEAR": "",
  "RESPONSIBLE_PERSON": ""
}'::jsonb);

-- ---------------------------
-- Marketing Information Config
-- ---------------------------

INSERT INTO public.module_configs (module_name, config) VALUES
('marketing_information', '{
  "META_TITLE": "Content OS",
  "META_DESCRIPTION": "A content platform.",
  "META_KEYWORDS": "content, platform",
  "SOCIAL_LINKS_X": "",
  "SOCIAL_LINKS_FACEBOOK": "",
  "SOCIAL_LINKS_INSTAGRAM": "",
  "SOCIAL_LINKS_YOUTUBE": ""
}'::jsonb);

-- ---------------------------
-- Landing Page Config
-- ---------------------------

INSERT INTO public.module_configs (module_name, config) VALUES
('landing_page', '{
  "HERO_TITLE": "Welcome",
  "HERO_SLOGAN": "Your platform. Your content.",
  "ACTIVE_TOP_BANNER": "false",
  "SOLUTION_SUBTITLE": "SOLUTIONS",
  "SOLUTION_TITLE": "What We Offer",
  "SOLUTION_DESCRIPTION": "Explore the tools and features that power your experience.",
  "HOW_IT_WORKS_1_SUBTITLE": "HOW IT WORKS",
  "HOW_IT_WORKS_1_TITLE": "Get Started",
  "HOW_IT_WORKS_2_SUBTITLE": "HOW IT WORKS",
  "HOW_IT_WORKS_2_TITLE": "Create and Manage",
  "HOW_IT_WORKS_3_SUBTITLE": "HOW IT WORKS",
  "HOW_IT_WORKS_3_TITLE": "Share and Grow",
  "HOW_IT_WORKS_1_DESCRIPTION": "Sign up and set up your account in a few steps.",
  "HOW_IT_WORKS_2_DESCRIPTION": "Create content, manage settings, and customize your experience.",
  "HOW_IT_WORKS_3_DESCRIPTION": "Share with your audience and grow your presence.",
  "FEATURES_SUBTITLE": "FEATURES",
  "FEATURES_TITLE": "Features",
  "FEATURES_DESCRIPTION": "Discover what you can do with the platform.",
  "COMPARISON_SUBTITLE": "COMPARISONS",
  "COMPARISON_TITLE": "Why Choose Us",
  "COMPARISON_DESCRIPTION": "A platform built for clarity and ease of use.",
  "COMPARISON_WITHOUT_TITLE": "Without a platform",
  "COMPARISON_WITH_TITLE": "With us",
  "CTA_BANNER_WITH_IMAGE_SUBTITLE": "CONTRIBUTE",
  "CTA_BANNER_WITH_IMAGE_TITLE": "Join Us",
  "CTA_BANNER_WITH_IMAGE_DESCRIPTION": "Create an account and start using the platform.",
  "PRICING_SUBTITLE": "PRICING",
  "PRICING_TITLE": "Choose Your Plan",
  "PRICING_DESCRIPTION": "Select a plan that fits your needs.",
  "FAQ_SUBTITLE": "FAQs",
  "FAQ_TITLE": "Frequently Asked Questions",
  "FAQ_DESCRIPTION": "Common questions and answers. Contact us if you need more help.",
  "PLANS_SUBTITLE": "PLANS",
  "PLANS_TITLE": "Choose Your Plan",
  "PLANS_DESCRIPTION": "Select a plan that fits your needs.",
  "CREDIT_PACKS_SUBTITLE": "CREDIT PACKS",
  "CREDIT_PACKS_TITLE": "Credit Packs",
  "CREDIT_PACKS_DESCRIPTION": "One-time purchase, use anytime.",
  "PAGE_PACK_SUBTITLE": "PAGE PACK",
  "PAGE_PACK_TITLE": "Page Pack",
  "PAGE_PACK_DESCRIPTION": "Get your space with custom options.",
  "FAQ_PRICING_DESCRIPTION": "Find answers about pricing and plans.",
  "CTA_BANNER_BIG_SUBTITLE": "GETTING STARTED",
  "CTA_BANNER_BIG_TITLE": "Get Started",
  "CTA_BANNER_BIG_DESCRIPTION": "Create your account and get started today."
}'::jsonb);

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: blog, File: 501_20260313_seed.sql
-- ---------------------------
-- MODULE NAME: Blog System Seed Data
-- MODULE DATE: 20260313
-- MODULE SCOPE: Initial Data
-- ---------------------------



-- ---------------------------
-- Create Blog Images Bucket
-- ---------------------------
INSERT INTO storage.buckets (
    id, 
    name,
    public,
    avif_autodetection,
    file_size_limit,
    allowed_mime_types
) VALUES (
    'blog_images',
    'blog_images',
    TRUE,
    FALSE,
    5242880, -- 5MB limit
    ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']::text[]
)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------
-- Seed Blog Topics
-- ---------------------------
-- Main Topics
INSERT INTO public.blog_topics (id, name, description) VALUES
    ('d5f7a000-0000-4000-a000-000000000001', 'Customer Success & Social Proof', 'Real-world customer outcomes and credibility-building stories'),
    ('d5f7a000-0000-4000-a000-000000000002', 'Education & Enablement', 'Practical learning content to help users succeed with the product'),
    ('d5f7a000-0000-4000-a000-000000000003', 'Product Communication', 'Feature updates, roadmap direction, and adoption guidance'),
    ('d5f7a000-0000-4000-a000-000000000004', 'Competitive Evaluation & Buyer Guidance', 'Decision-support content for product comparisons and buying choices')
ON CONFLICT (id) DO NOTHING;

-- Customer Success & Social Proof Subtopics
INSERT INTO public.blog_topics (id, name, description, parent_id) VALUES
    ('d5f7a000-0000-4000-a000-000000000101', 'Customer Success Stories', 'Narratives showing how customers solved key problems and reached measurable outcomes', 'd5f7a000-0000-4000-a000-000000000001'),
    ('d5f7a000-0000-4000-a000-000000000102', 'Case Studies', 'Structured deep-dives into implementation, impact, and lessons learned', 'd5f7a000-0000-4000-a000-000000000001')
ON CONFLICT (id) DO NOTHING;

-- Education & Enablement Subtopics
INSERT INTO public.blog_topics (id, name, description, parent_id) VALUES
    ('d5f7a000-0000-4000-a000-000000000201', 'Educational Guides', 'Foundational explainers and actionable guidance for target use cases', 'd5f7a000-0000-4000-a000-000000000002'),
    ('d5f7a000-0000-4000-a000-000000000202', 'How-to Tutorials', 'Step-by-step walkthroughs for completing specific jobs in the product', 'd5f7a000-0000-4000-a000-000000000002'),
    ('d5f7a000-0000-4000-a000-000000000203', 'Feature Walkthroughs by Use Case', 'Practical examples of feature usage across roles and scenarios', 'd5f7a000-0000-4000-a000-000000000002'),
    ('d5f7a000-0000-4000-a000-000000000204', 'Common Mistakes & Troubleshooting', 'Frequent pitfalls, root causes, and guided fixes', 'd5f7a000-0000-4000-a000-000000000002')
ON CONFLICT (id) DO NOTHING;

-- Product Communication Subtopics
INSERT INTO public.blog_topics (id, name, description, parent_id) VALUES
    ('d5f7a000-0000-4000-a000-000000000301', 'Product Updates', 'Release-focused updates framed around customer benefits and outcomes', 'd5f7a000-0000-4000-a000-000000000003'),
    ('d5f7a000-0000-4000-a000-000000000302', 'Roadmap Previews', 'Forward-looking posts that explain upcoming direction and priorities', 'd5f7a000-0000-4000-a000-000000000003'),
    ('d5f7a000-0000-4000-a000-000000000303', 'Adoption Announcements & Migration Tips', 'Enablement content for rollout, onboarding, and transition planning', 'd5f7a000-0000-4000-a000-000000000003')
ON CONFLICT (id) DO NOTHING;

-- Competitive Evaluation & Buyer Guidance Subtopics
INSERT INTO public.blog_topics (id, name, description, parent_id) VALUES
    ('d5f7a000-0000-4000-a000-000000000401', 'Versus Comparison Posts', 'Head-to-head comparisons that clarify key differences and fit', 'd5f7a000-0000-4000-a000-000000000004'),
    ('d5f7a000-0000-4000-a000-000000000402', 'Buyer Decision Frameworks', 'Decision criteria and scoring approaches for selecting a solution', 'd5f7a000-0000-4000-a000-000000000004'),
    ('d5f7a000-0000-4000-a000-000000000403', 'When to Choose X vs Y Scenarios', 'Scenario-based guidance to choose the right option for constraints and goals', 'd5f7a000-0000-4000-a000-000000000004')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------
-- Seed Sample Blog Post
-- ---------------------------
INSERT INTO public.blog_posts (
    title,
    description,
    content,
    topic_id,
    is_admin_approved,
    is_user_published
) VALUES (
    'Welcome to Our Blog',
    'Learn about our blog system and how to use it effectively',
    '# Welcome to Our Blog

This is a sample blog post that demonstrates the capabilities of our blog system.

## Features

- Rich text editing
- Beautiful and responsive design
- SEO optimization
- And much more!

Get started by creating your first blog post today!',
    'd5f7a000-0000-4000-a000-000000000202', -- How-to Tutorials subtopic
    true,
    true
)
ON CONFLICT DO NOTHING;

-- ---------------------------
-- Module Configs
-- ---------------------------

INSERT INTO public.module_configs (module_name, config) VALUES
(
    'blog',
    '{
  "BLOG_POST_SEO_META_TITLE": "Blog",
  "BLOG_POST_SEO_META_DESCRIPTION": "Here you can find all published blog posts.",
  "BLOG_POST_SEO_META_TAGS": "blog, articles, news, content"
}'::jsonb
)
ON CONFLICT (module_name) DO NOTHING;

-- ---------------------------
-- END OF FILE
-- ---------------------------


-- Module: user-auth, File: 602_20250310_cron.sql
-- ---------------------------
-- MODULE NAME: User Auth
-- MODULE DATE: 20250310
-- MODULE SCOPE: Cron Jobs
-- ---------------------------



-- ---------------------------
-- Install pg_cron Extension
-- ---------------------------
-- Required for scheduled deletion of expired refresh tokens.
-- On Supabase 1.169.8+, pg_cron must be in pg_catalog schema.
CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog;

-- ---------------------------
-- Schedule: Delete Expired Refresh Tokens
-- Runs every Saturday at 3:30 AM (GMT)
-- ---------------------------

SELECT cron.schedule(
  'delete-expired-refresh-tokens', -- name of the cron job
  '30 3 * * 6', -- Saturday at 3:30 AM (GMT) - cron syntax: minute hour day month weekday
  $$ DELETE FROM public.refresh_tokens WHERE expires_at < now() $$
);

-- ---------------------------
-- END OF FILE
-- ---------------------------


COMMIT;